name: Build and deploy Flashcards App on push

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy-flashcards-generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clear cache
      working-directory: ./flashcards-generator
      run: rm -rf node_modules && npm cache clean --force
    - name: install dependencies
      working-directory: ./flashcards-generator
      run: npm install
    - name: Run npm build
      working-directory: ./flashcards-generator
      env:
        DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
        API_HOSTNAME: ${{ secrets.API_HOSTNAME }}
        API_KEY: ${{ secrets.API_KEY }}
      run: npm run build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: master
        FOLDER: flashcards-generator/dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
